[2023-04-14 12:50:56,801] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: spotify_final_dag.create_table 2023-04-14T06:40:00+00:00 [queued]>
[2023-04-14 12:50:57,462] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: spotify_final_dag.create_table 2023-04-14T06:40:00+00:00 [queued]>
[2023-04-14 12:50:57,612] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-14 12:50:57,705] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2023-04-14 12:50:57,751] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-14 12:50:58,102] {taskinstance.py:1089} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-14T06:40:00+00:00
[2023-04-14 12:50:58,150] {standard_task_runner.py:52} INFO - Started process 55 to run task
[2023-04-14 12:50:58,170] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_final_dag', 'create_table', '2023-04-14T06:40:00+00:00', '--job-id', '60', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmpzzh9oupr', '--error-file', '/tmp/tmp1wfpovz2']
[2023-04-14 12:50:58,198] {standard_task_runner.py:77} INFO - Job 60: Subtask create_table
[2023-04-14 12:50:59,447] {logging_mixin.py:104} INFO - Running <TaskInstance: spotify_final_dag.create_table 2023-04-14T06:40:00+00:00 [running]> on host 75651b8604e6
[2023-04-14 12:51:00,878] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_final_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T06:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T06:40:00+00:00
[2023-04-14 12:51:00,942] {postgres.py:69} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS top_songs (
            song_date VARCHAR(200),
            song_name VARCHAR(200),
            artist_name VARCHAR(200)
            )
[2023-04-14 12:51:01,119] {base.py:78} INFO - Using connection to: id: postgre_sql. Host: postgres, Port: 5432, Schema: spotify_db, Login: airflow, Password: XXXXXXXX, extra: None
[2023-04-14 12:51:01,215] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "spotify_db" does not exist

[2023-04-14 12:51:01,263] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_final_dag, task_id=create_table, execution_date=20230414T064000, start_date=20230414T125056, end_date=20230414T125101
[2023-04-14 12:51:01,974] {local_task_job.py:146} INFO - Task exited with return code 1
