[2023-04-15 07:42:44,303] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: spotify_final_dag.create_table 2023-04-15T07:41:23.258545+00:00 [queued]>
[2023-04-15 07:42:44,565] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: spotify_final_dag.create_table 2023-04-15T07:41:23.258545+00:00 [queued]>
[2023-04-15 07:42:44,566] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2023-04-15 07:42:44,585] {taskinstance.py:1069} INFO - Starting attempt 2 of 2
[2023-04-15 07:42:44,586] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2023-04-15 07:42:44,690] {taskinstance.py:1089} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-15T07:41:23.258545+00:00
[2023-04-15 07:42:44,727] {standard_task_runner.py:52} INFO - Started process 51 to run task
[2023-04-15 07:42:44,777] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_final_dag', 'create_table', '2023-04-15T07:41:23.258545+00:00', '--job-id', '144', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/spotify_final_dag.py', '--cfg-path', '/tmp/tmp8ldynvh0', '--error-file', '/tmp/tmpjts5ssil']
[2023-04-15 07:42:44,793] {standard_task_runner.py:77} INFO - Job 144: Subtask create_table
[2023-04-15 07:42:45,250] {logging_mixin.py:104} INFO - Running <TaskInstance: spotify_final_dag.create_table 2023-04-15T07:41:23.258545+00:00 [running]> on host 75651b8604e6
[2023-04-15 07:42:45,821] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=spotify_final_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-15T07:41:23.258545+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-15T07:41:23.258545+00:00
[2023-04-15 07:42:45,917] {postgres.py:69} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS top_songs (
            id SERIAL PRIMARY KEY,
            song_date VARCHAR(200),
            song_name VARCHAR(200),
            artist_name VARCHAR(200)
            );
[2023-04-15 07:42:46,121] {base.py:78} INFO - Using connection to: id: postgre_sql. Host: postgres, Port: 5432, Schema: suppliers, Login: airflow, Password: XXXXXXXX, extra: None
[2023-04-15 07:42:46,233] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "suppliers" does not exist

[2023-04-15 07:42:46,250] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=spotify_final_dag, task_id=create_table, execution_date=20230415T074123, start_date=20230415T074244, end_date=20230415T074246
[2023-04-15 07:42:46,821] {local_task_job.py:146} INFO - Task exited with return code 1
